<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="gazebo/common_inertias.xacro"/>

    <xacro:property name="disc_height" value="0.005"/>
    <xacro:property name="disc_radius" value="0.07"/>
    <xacro:property name="disc_mass" value="0.05"/>


    <xacro:property name="wheel_width" value="0.025"/>
    <xacro:property name="wheel_radius" value="0.024"/>
    <xacro:property name="wheel_mass" value="0.01"/>

    <xacro:property name="caster_wheel_radius" value="${wheel_radius/2}"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.06"/>
    <xacro:property name="caster_wheel_offset_z" value="${caster_wheel_radius}"/>

    <xacro:property name="imu_size" value="0.01"/>
    <xacro:property name="imu_mass" value="0.01"/>

    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="blue">
        <color rgba="0 1 1 1"/>
    </material>

    <material name="red">
        <color rgba="0.596078431372549 0.0 0.00784313725490196 1.0"/>
    </material>

    <link name="base_link">
        <xacro:cylinder_inertial mass="${disc_mass}" radius="${disc_radius}" length="${disc_height}" rotation="0"/>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${disc_radius}" length="${disc_height}"/>
            </geometry>

            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${disc_radius}" length="${disc_height}"/>
            </geometry>
        </collision>
    </link>

    <xacro:macro name="wheel" params="prefix y_reflect">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertial mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_width}"
                                     rotation="${pi/2}"/>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="0 ${y_reflect*(disc_radius+(wheel_width/2))} 0" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <xacro:wheel prefix="front_left" y_reflect="1"/>
    <xacro:wheel prefix="front_right" y_reflect="-1"/>


    <link name="base_footprint"/>
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

</robot>